substitutions:
  #device_id: "[device id]"
  friendly_name: "ESP Lavalamp"
  color_order: "GRB" # GRB, BGR, RGBW, etc.
  led_chip: "ws2812x" # sk6812
  update_interval: "10" # 20mspf = 50fps

packages:
  lavalamp: "github://HaLo2FrEeEk/ESPHome_NeoPixel_Lavalamp/esp8266-lavalamp.yaml"

esphome:
  name_add_mac_suffix: true

light:
  - id: !extend lavalamp
    pin: 3 # whatever pin you're using. Default is 1
